all:
  children:
    control_plane:
      hosts:
        cp1:
          ansible_host: 10.10.2.9
        cp2:
          ansible_host: 10.10.2.10
        cp3:
          ansible_host: 10.10.2.11 
    workers:
      hosts:
        worker1:
          ansible_host: 10.10.2.12
        worker2:
          ansible_host: 10.10.2.13
        worker3:
          ansible_host: 10.10.2.14
