all:
  children:
    master:
      hosts:
        master1:
          ansible_host: 10.10.2.9
        master2:
          ansible_host: 10.10.2.10
        master3:
          ansible_host: 10.10.2.11 
    workers:
      hosts:
        worker1:
          ansible_host: 10.10.2.12
        worker2:
          ansible_host: 10.10.2.13
        worker3:
          ansible_host: 10.10.2.14
