all:
  children:
    managers:
      hosts:
        manager1:
          ansible_host: 10.10.2.22
        manager2:
          ansible_host: 10.10.2.23
        manager3:
          ansible_host: 10.10.2.24
    workers:
      hosts:
        worker1:
          ansible_host: 10.10.2.26
        worker2:
          ansible_host: 10.10.2.25
