---
- name: Remove old Wazuh Docker volumes
  community.docker.docker_volume:
    name: "{{ item }}"
    state: absent
  loop:
    - wazuh_manager_etc
    - wazuh_manager_integrations
    - wazuh_manager_api_conf
    - wazuh_indexer_data
    - wazuh_dashboard_data
    - wazuh_certs
    - wazuh_nginx_conf
    
- name: Ensure NFS volume is mounted
  ansible.builtin.mount:
    path: /share
    src: "{{ nfs_server }}:/share"
    fstype: nfs
    opts: rw,sync
    state: mounted
    
- name: Create Docker overlay network
  community.docker.docker_network:
    name: wazuh-net
    driver: overlay
    attachable: yes
    state: present

- name: Ensure local build directories exist for each Indexer
  ansible.builtin.file:
    path: "/tmp/{{ item.name }}"
    state: directory
    mode: "0755"
  loop: "{{ indexer_nodes }}"

- name: Create Dockerfile for each Indexer in local build directory
  ansible.builtin.copy:
    dest: "/tmp/{{ item.name }}/Dockerfile"
    content: |
      FROM wazuh/wazuh-indexer:4.13.0-beta2
      COPY certs /usr/share/wazuh-indexer/config/certs
      RUN chmod 640 /usr/share/wazuh-indexer/config/certs/*.pem && \
          chmod 600 /usr/share/wazuh-indexer/config/certs/*-key.pem
  loop: "{{ indexer_nodes }}"

- name: Ensure certs directory exists in local build path
  ansible.builtin.file:
    path: "/tmp/{{ item.name }}/certs"
    state: directory
    mode: "0755"
  loop: "{{ indexer_nodes }}"

- name: Copy certificates from NFS to local build directory
  ansible.builtin.copy:
    src: "/share/wazuh/config/wazuh_indexer_ssl_certs/"
    dest: "/tmp/{{ item.name }}/certs/"
    owner: root
    group: root
    mode: "0640"
  loop: "{{ indexer_nodes }}"

- name: Build custom Wazuh Indexer images from local path
  community.docker.docker_image:
    path: "/tmp/{{ item.name }}"
    name: "{{ item.name }}-custom"
    tag: "4.13.0-beta2"
    push: no
  loop: "{{ indexer_nodes }}"

- name: Render Wazuh stack template
  ansible.builtin.template:
    src: roles/deploy_wazuh/templates/wazuh-stack.yml.j2
    dest: /tmp/wazuh-stack.yml

- name: Deploy Wazuh stack
  community.docker.docker_stack:
    name: wazuh
    state: present
    compose:
      - /tmp/wazuh-stack.yml
  environment:
    UID: "{{ ansible_user_uid }}"
    GID: "{{ ansible_user_gid }}"
  register: wazuh_stack

- name: Wait for Wazuh services to be healthy
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: 443
    delay: 10
    timeout: 600
    state: started

- name: Deploy Nginx reverse proxy
  community.docker.docker_container:
    name: wazuh-nginx
    image: nginx:mainline
    state: started
    restart_policy: always
    ports:
      - "1519:1519"
    volumes:
      - /share/wazuh/config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

























