---
- name: Remove old Wazuh Docker volumes
  community.docker.docker_volume:
    name: "{{ item }}"
    state: absent
  loop:
    - wazuh_manager_etc
    - wazuh_manager_integrations
    - wazuh_manager_api_conf
    - wazuh_indexer_data
    - wazuh_dashboard_data
    - wazuh_certs
    - wazuh_nginx_conf
    
- name: Ensure NFS volume is mounted
  ansible.builtin.mount:
    path: /share
    src: "{{ nfs_server }}:/share"
    fstype: nfs
    opts: rw,sync
    state: mounted
    
- name: Create Docker overlay network
  community.docker.docker_network:
    name: wazuh-net
    driver: overlay
    attachable: yes
    state: present

- name: Ensure Docker build directories exist
  ansible.builtin.file:
    path: "/tmp/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - dockerfile1
    - dockerfile2
    - dockerfile3

- name: Render Dockerfile for each Indexer
  ansible.builtin.template:
    src: "roles/deploy_wazuh/templates/Dockerfile.j2"
    dest: "/tmp/{{ item }}/Dockerfile"
  loop:
    - dockerfile1
    - dockerfile2
    - dockerfile3

- name: Copy certificates into Docker build directories
  ansible.builtin.copy:
    src: "/share/wazuh/config/wazuh_indexer_ssl_certs/"
    dest: "/tmp/{{ item }}/certs/"
    owner: root
    group: root
    mode: '0640'
  loop:
    - dockerfile1
    - dockerfile2
    - dockerfile3


- name: Render Wazuh stack template
  ansible.builtin.template:
    src: roles/deploy_wazuh/templates/wazuh-stack.yml.j2
    dest: /tmp/docker-compose.yml

- name: Deploy Wazuh stack with Docker Compose V2
  community.docker.docker_compose_v2:
    project_src: /tmp
    files:
      - wazuh-stack.yml
    state: present
    pull: always
    recreate: yes
  environment:
    UID: "{{ ansible_user_uid }}"
    GID: "{{ ansible_user_gid }}"
  register: wazuh_stack

- name: Wait for Wazuh services to be healthy
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: 443
    delay: 10
    timeout: 600
    state: started




































