---
- name: Remove old Wazuh Docker volumes
  community.docker.docker_volume:
    name: "{{ item }}"
    state: absent
  loop:
    - wazuh_manager_etc
    - wazuh_manager_integrations
    - wazuh_manager_api_conf
    - wazuh_indexer_data
    - wazuh_dashboard_data
    - wazuh_certs
    - wazuh_nginx_conf
    
- name: Ensure NFS volume is mounted
  ansible.builtin.mount:
    path: /share
    src: "{{ nfs_server }}:/share"
    fstype: nfs
    opts: rw,sync
    state: mounted
    
- name: Create Docker overlay network
  community.docker.docker_network:
    name: wazuh-net
    driver: overlay
    attachable: yes
    state: present

- name: Render Wazuh stack template
  ansible.builtin.template:
    src: roles/deploy_wazuh/templates/wazuh-stack.yml.j2
    dest: /tmp/wazuh-stack.yml

- name: Deploy Wazuh stack
  community.docker.docker_stack:
    name: wazuh
    state: present
    compose:
      - /tmp/wazuh-stack.yml
  environment:
    UID: "{{ ansible_user_uid }}"
    GID: "{{ ansible_user_gid }}"
  register: wazuh_stack

- name: Wait for Wazuh services to be healthy
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: 443
    delay: 10
    timeout: 600
    state: started

- name: Deploy Nginx reverse proxy
  community.docker.docker_container:
    name: wazuh-nginx
    image: nginx:alpine
    state: started
    restart_policy: always
    ports:
      - "1514:1514"
    volumes:
      - /share/wazuh/certs:/etc/nginx/certs:ro
      - /share/wazuh/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro















