---
- name: Ensure NFS volume is mounted
  ansible.builtin.mount:
    path: /share
    src: "{{ nfs_server }}:/share"
    fstype: nfs
    opts: rw,sync
    state: mounted

- name: Create Docker overlay network
  community.docker.docker_network:
    name: wazuh-net
    driver: overlay
    attachable: yes
    state: present

- name: Generate self-signed certificates
  ansible.builtin.openssl_certificate:
    path: /share/certs/wazuh.crt
    privatekey_path: /share/certs/wazuh.key
    common_name: "{{ inventory_hostname }}"
    provider: selfsigned
  become: true

- name: Deploy Wazuh stack
  community.docker.docker_stack:
    name: wazuh
    state: present
    compose:
      - "{{ playbook_dir }}/roles/wazuh_setup/templates/wazuh-stack.yml.j2"
  register: wazuh_stack

- name: Wait for Wazuh services to be healthy
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: 443
    delay: 10
    timeout: 300
    state: started

- name: Deploy Nginx reverse proxy
  community.docker.docker_container:
    name: wazuh-nginx
    image: nginx:alpine
    state: started
    restart_policy: always
    ports:
      - "443:443"
    volumes:
      - /share/certs:/etc/nginx/certs:ro
      - /share/nginx.conf:/etc/nginx/conf.d/default.conf:ro
