- name: Remove old Wazuh Docker volumes
  community.docker.docker_volume:
    name: "{{ item }}"
    state: absent
  loop:
    - wazuh_manager_etc
    - wazuh_manager_integrations
    - wazuh_manager_api_conf
    - wazuh_indexer_data
    - wazuh_dashboard_data
    - wazuh_certs
    - wazuh_nginx_conf

- name: Create Docker overlay network
  community.docker.docker_network:
    name: wazuh-net
    driver: overlay
    attachable: yes
    state: present

- name: Create all Wazuh secrets in Swarm
  community.docker.docker_secret:
    name: "{{ item.name }}"
    secret: "{{ item.value }}"
    state: present
  loop:
    - { name: wazuh_api_credentials, value: "{{ wazuh_api_username }}:{{ wazuh_api_password }}" }
    - { name: dashboard_credentials, value: "{{ dashboard_username }}:{{ dashboard_password }}" }
    - { name: indexer_credentials, value: "{{ indexer_username }}:{{ indexer_password }}" }

- name: Render Wazuh stack template
  ansible.builtin.template:
    src: roles/deploy_wazuh/templates/wazuh-stack.yml.j2
    dest: /tmp/wazuh-stack.yml

- name: Deploy Wazuh stack with Docker Swarm
  community.docker.docker_stack:
    name: wazuh
    state: present
    compose:
      - /tmp/wazuh-stack.yml
  environment:
    UID: "{{ ansible_user_uid }}"
    GID: "{{ ansible_user_gid }}"
  register: wazuh_stack












































