name: Deploy Docker Swarm

on:
  workflow_dispatch:  
         

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pip
          pip install ansible jsondiff

      - name: Test connectivity to target VMs
        run: |
          ansible all -i all -m ping

      - name: Run Ansible Playbook
        working-directory: ansible/deploy-swarm
        run: |
          ansible-playbook -i inventory/inventory.yaml deployKube.yml
