name: Deploy Docker Swarm

on:
  workflow_dispatch:  
  push:
    branches:
      - main           

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          python -m venv ~/ansible-venv
          source ~/ansible-venv/bin/activate
          pip install --upgrade pip
          pip install ansible community.docker jsondiff

      - name: Test connectivity to target VMs
        run: |
          ansible all -i all -m ping

      - name: Run Ansible Playbook
        working-directory: ansible/deploy-swarm
        run: |
          source ~/ansible-venv/bin/activate
          ansible-playbook -i inventory/inventory.yaml deploy.yml
