name: Deploy Docker Wazuh Cluster

on:
  workflow_dispatch:  
         

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pip
          pip install ansible jsondiff selenium pytest ansible-lint yamllint
    
      - name: Run yamllint
        run: yamllint .

      - name: Run ansible-lint
        run: ansible-lint ansible/

    
      - name: Trivy scan on Wazuh Manager
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: wazuh-manager:latest
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Trivy scan on Wazuh Indexer
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: wazuh-indexer:latest
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Trivy scan on Wazuh Dashboard
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: wazuh-dashboard:latest
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

    
      - name: Install Chrome & Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Run Selenium tests
        run: |
          pytest tests/selenium/ --maxfail=1 --disable-warnings -q

      - name: Test connectivity to target VMs
        run: |
          ansible all -i inventory/inventory.yaml -m ping

      - name: Run Ansible Playbook
        working-directory: ansible/deploy-swarm
        env:
          WAZUH_API_USERNAME: ${{ secrets.WAZUH_API_USERNAME }}
          WAZUH_API_PASSWORD: ${{ secrets.WAZUH_API_PASSWORD }}
          DASHBOARD_USERNAME: ${{ secrets.DASHBOARD_USERNAME }}
          DASHBOARD_PASSWORD: ${{ secrets.DASHBOARD_PASSWORD }}
          INDEXER_USERNAME: ${{ secrets.INDEXER_USERNAME }}
          INDEXER_PASSWORD: ${{ secrets.INDEXER_PASSWORD }}
        run: |
          ansible-playbook -i inventory/inventory.yaml deploy.yml \
          -e "wazuh_api_username=$WAZUH_API_USERNAME \
          wazuh_api_password=$WAZUH_API_PASSWORD \
          dashboard_username=$DASHBOARD_USERNAME \
          dashboard_password=$DASHBOARD_PASSWORD \
          indexer_username=$INDEXER_USERNAME \
          indexer_password=$INDEXER_PASSWORD"

