name: Deploy Docker Swarm

on:
  workflow_dispatch:  
  push:
    branches:
      - main           

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Start SSH agent and add all keys
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ secrets.MANAGER1_PRIVATE_KEY }}" | ssh-add -
          echo "${{ secrets.MANAGER2_PRIVATE_KEY }}" | ssh-add -
          echo "${{ secrets.MANAGER3_PRIVATE_KEY }}" | ssh-add -
          echo "${{ secrets.WORKER1_PRIVATE_KEY }}" | ssh-add -
          echo "${{ secrets.WORKER2_PRIVATE_KEY }}" | ssh-add -
        shell: bash

      - name: Run Ansible Playbook
        working-directory: ansible/deploy-swarm
        run: |
          ansible-playbook -i inventory/inventory.yaml deploy.yml
