name: Deploy Docker Wazuh Cluster

on:
  workflow_dispatch:  
         

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pip
          pip install ansible jsondiff

      - name: Test connectivity to target VMs
        run: |
          ansible all -i inventory/inventory.yaml -m ping

      - name: Run Ansible Playbook
        working-directory: ansible/deploy-swarm
        run: |
          ansible-playbook -i inventory/inventory.yaml deploy.yml -e "
          api_username=${{ secrets.WAZUH_API_USERNAME }}
          api_password=${{ secrets.WAZUH_API_PASSWORD }}
          dashboard_username=${{ secrets.DASHBOARD_USERNAME }}
          dashboard_password=${{ secrets.DASHBOARD_PASSWORD }}
          indexer_username=${{ secrets.INDEXER_USERNAME }}
          indexer_password=${{ secrets.INDEXER_PASSWORD }}"


