name: basicwork flow
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test-runner:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: run checkout
        uses: actions/checkout@v3
      - name: install ansible
        run: |
          sudo apt update
          sudo apt install ansible
